# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywCoWsTskga9inl9ScP_lb-FKMrcOl1X
"""

pip install langdetect

from langdetect import detect

def detect_language(text):
    return detect(text)

text = "സുഖമാണോ"  # Malayalam for "How are you"

codes = {
    'ar': 'Arabic', 'sq': 'Albanian', 'bn': 'Bangla', 'bh': 'Bhojpuri',
    'bg': 'Bulgarian', 'cs': 'Czech', 'da': 'Danish', 'de': 'German',
    'en': 'English', 'fr': 'French', 'el': 'Greek', 'hi': 'Hindi',
    'id': 'Indonesian', 'it': 'Italian', 'ja': 'Japanese', 'kn': 'Kannada',
    'ko': 'Korean', 'la': 'Latin', 'mr': 'Marathi', 'ml': 'Malayalam',
    'nl': 'Dutch', 'te': 'Telugu', 'ta': 'Tamil', 'cy': 'Welsh'
}

language_code = detect_language(text)
language = codes.get(language_code, "Unknown Language")
print("The language of the text is:", language)